#===========================================================#
# This file contains configuration to customize the website #
#===========================================================#

#---------------------------------------------------------#
# You can edit the configuration in the following section #
#---------------------------------------------------------#

# Name of your site (displayed in the header)
name: Locus Reference Genomic

# Short description (displayed in the meta)
description: LRG sequences provide a stable genomic DNA framework for reporting variants with a permanent ID and core content that never changes.

# Short description (displayed in the homepage)
description2: "A Locus Reference Genomic (LRG) record contains stable reference sequences for reporting sequence variants with clinical implications. LRG are manually curated, have permanent identifiers and core content that never changes"

# Tag line (displayed in the header)
tag_line: Stable reference sequences for reporting variants

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: /images/lrg_logo.png
avatar: /images/lrg_logo.png

# Search label
search-label: "Search LRGs"

# LRG counts (used in FAQ) - Can be edited
lrg-date: "September 2016"
lrg-created: "900"
lrg-public: "665"
lrg-schema: "1.9"

#--------------------------------------------------------#
# Configuration below is optional - NO NEED TO CHANGE IT #
#--------------------------------------------------------#

# Your website URL
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Others baseurls
baseurl_bootstrap:  "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6"
baseurl_googleapis: "https://ajax.googleapis.com/ajax/libs"


#-- Variables for javascript --#

# URLs
rest_url_38: "http://rest.ensembl.org/vep/human/hgvs/"
rest_url_37: "http://grch37.rest.ensembl.org/vep/human/hgvs/"
rest_lrg:    "http://www.ebi.ac.uk/ebisearch/ws/rest/lrg"

conseq_url:  "http://www.ensembl.org/info/genome/variation/predicted_data.html#"

# 38
ens_url:        "http://www.ensembl.org/Homo_sapiens/Location/View?r=###LOC###&contigviewbottom=url:ftp://ftp.ebi.ac.uk/pub/databases/lrgex/.ensembl_internal/###ID###_###ASSEMBLY###.gff=labels"
ens_gene_url:   "http://www.ensembl.org/Homo_sapiens/Gene/Summary?g="
ens_trans_url:  "http://www.ensembl.org/Homo_sapiens/Transcript/Summary?t="
ens_var_url:    "http://www.ensembl.org/Homo_sapiens/Variation/Explore?v="

#37
ens_url_37:       "http://grch37.ensembl.org/Homo_sapiens/Location/View?r=###LOC###&contigviewbottom=url:ftp://ftp.ebi.ac.uk/pub/databases/lrgex/.ensembl_internal/###ID###_###ASSEMBLY###.gff=labels"
ens_gene_url_37:  "http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?g="
ens_trans_url_37: "http://grch37.ensembl.org/Homo_sapiens/Transcript/Summary?t="
ens_var_url_37:   "http://grch37.ensembl.org/Homo_sapiens/Variation/Explore?v="


ncbi_url: "http://www.ncbi.nlm.nih.gov/mapview/maps.cgi?taxid=9606&CHR=###CHR###&BEG=###START###&END=###END###"
ucsc_url: "http://genome.ucsc.edu/cgi-bin/hgTracks?clade=mammal&org=Human&position=chr###LOC###"
hgnc_url: "http://www.genenames.org/cgi-bin/gene_symbol_report?match="

ref_assembly:   "GRCh38"
lrg_ftp:        "http://ftp.ebi.ac.uk/pub/databases/lrgex/test/"
#lrg_ftp:        "http://ftp.ebi.ac.uk/pub/databases/lrgex/"
lrg_json_file : "/json_index/lrg_index.json"
#lrg_json_file:  "http://ftp.ebi.ac.uk/pub/databases/lrgex/.lrg_index/lrg_index.json"
#------------------------------#


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  embl-ebi: "http://www.ebi.ac.uk"
  ncbi: "http://www.ncbi.nlm.nih.gov"


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge

permalink: /:title/

# The release of Jekyll used
version: 3.3.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed or expanded using :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

collections:
    faq_groups:
        output: true
        permalink: /faq_group/:path/
    faq_categories:
        output: true
        permalink: /faq_category/:path/
    faq:
        output: true
        permalink: /faq/:path/
    web-service:
        output: true
defaults:
    -
        scope: 
            type: "faq"
            path: "faq"
        values:
            layout: "faq"


# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
